# ============================================================
#  Urbvan - Configuración de base de datos
#  Ubicación: src/main/resources/db.properties
#  IMPORTANTE: no subir este archivo a repositorios públicos
# ============================================================

db.url=jdbc:mysql://localhost:3306/urbvan?useSSL=false&serverTimezone=America/Mexico_City&characterEncoding=UTF-8&useUnicode=true
db.usuario=root
db.contrasena=rex4828f
